language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

branches:
    only:
    - master

install: 'pip install --quiet tox tox-travis coveralls python-coveralls'

script: tox

after_success:
    - coveralls
