language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

branches:
    only:
    - master

install: 'pip install --quiet --use-mirrors tox-travis python-coveralls'

script: tox

after_script:
    coveralls
