language: python

env:
- TOXENV=py27-dj18
- TOXENV=py27-dj19
- TOXENV=py27-dj110
- TOXENV=py34-dj18
- TOXENV=py34-dj19
- TOXENV=py34-dj110
- TOXENV=py35-dj18
- TOXENV=py35-dj19
- TOXENV=py35-dj110
- TOXENV=cov

branches:
    only:
    - master

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
  fi
